on: push
name: Build
jobs:
  web-deploy:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install
      run: npm i

    - name: Build
      run: npm run build

